version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: iEYDxCDiCL
      MYSQL_DATABASE: quiz

  api:
    depends_on:
      - mysql
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8080:8080"

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"

